### PR TITLE
Format JSON output

### PR DESCRIPTION
**Pull request by damms005**
This PR adds a new feature that ensures output that are JSON are nicely formatted

### CODE REVIEW

**Comment by tmdh** [comment]
Can you give me a tinker script to test?

**Comment by damms005** [comment]
@tmdh please clarify what you mean by "tinker script"

The PR simply ensures that when you do something like `User::all()->toJSON()` or run any code that results in a JSON-like output, the output is a nicely-formatted JSON, rather than being squished together.

Refer to the before-and-after screenshots below:

## BEFORE:
image

## AFTER:
image

**Comment by tmdh** [comment]
LGTM

**Comment by damms005** [comment]
@tmdh  post-merge comment: can I add a voice to [PR 36](https://github.com/tmdh/laravel-kit/pull/36)? It is a good addition for Linux folks. I tested it and it worked flawlessly!

**Comment by luanfreitasdev** [comment]
There's no way to know exactly. But I believe that many prefer to install the deb to convert it. Looking for the empty icon is not practical.

**Pull request merged**
