### PR TITLE
Show errors from tinker & fix bug

### LINKED ISSUE #27: How to display errors in Tinker?
Hey Tareque! 

Thanks for making this application. I really like the concept and especially the Tinker part. It gives me the feeling and conveniences of a text editor instead of the terminal. 

There's one thing that you should absolutely consider building – and that's Tinker error messages. Now, the 'Tinkering...' keeps going, where there's in fact an error message.

Error messages would greatly improve the usefulness of this app and I'd appreciate it if you could consider developing this.

Thanks a lot and have a good weekend!

Ralph

### PR DESCRIPTION
**Pull request by evaleries**
This PR will fix the bug from `yarn run dev:one` (https://github.com/sveltejs/svelte-loader/issues/188) and (#27)

Closes #27

### CODE REVIEW

**Comment by tmdh** [comment]
Error in Linux for any input:
```
ErrorException with message 'fwrite(): Send of 6 bytes failed with errno=32 Broken pipe'
```

**Comment by evaleries** [comment]
This PR should normally work on Windows.

I haven't tested this yet on Linux. Maybe you can help me solve this problem?

Thanks

**Comment by tmdh** [comment]
The current implementation is not an optimal way to get tinker output. I pushed a new implementation to `master` branch. Can you please check if it works on Windows? It works on Linux.

**Comment by evaleries** [comment]
> The current implementation is not an optimal way to get tinker output. I pushed a new implementation to `master` branch. Can you please check if it works on Windows? It works on Linux.

It's working fine, good job. I'll close this PR

**Pull request closed without merging**
